/**
 * Post-deploy verification for the Compass receipt-signer running on Phala
 * dstack TDX. Pass the deployed CVM URL via argv[2]:
 *
 *   ts-node enclave/phala/scripts/verify-deploy.ts https://<cvm>.phala.network
 *
 * Asserts:
 *   - GET /health returns source: "tee"
 *   - GET /v1/attestation returns ethAddress, composeHash, quoteHex, signatureChain
 *   - extractReportData(quoteHex) is well-formed
 *   - verifyReportDataBinding(quoteHex, ethAddress, composeHash) does not throw
 *
 * Writes the deployment evidence to docs/notes/phala-deployment.md.
 */
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { verifyReportDataBinding } from "../../src/verify-attestation";

type AttestationResponse = {
  ethAddress: string;
  composeHash: string;
  appId: string;
  instanceId: string;
  reportDataHex: string;
  quoteHex: string;
  eventLog: string;
  signatureChainHex: string[];
  boundAt: number;
};

type HealthResponse = {
  status: string;
  signer: string;
  source: "tee" | "env";
};

async function main() {
  const baseUrl = process.argv[2];
  if (!baseUrl) {
    console.error("Usage: ts-node verify-deploy.ts <baseUrl>");
    process.exit(2);
  }

  console.log(`[verify-deploy] target: ${baseUrl}`);

  const healthRes = await fetch(`${baseUrl}/health`, {
    signal: AbortSignal.timeout(15_000),
  });
  if (!healthRes.ok) {
    throw new Error(`/health returned ${healthRes.status}`);
  }
  const health = (await healthRes.json()) as HealthResponse;
  console.log(`[verify-deploy] /health source=${health.source} signer=${health.signer}`);
  if (health.source !== "tee") {
    throw new Error(`expected source=tee on prod deploy, got ${health.source}`);
  }

  const attRes = await fetch(`${baseUrl}/v1/attestation`, {
    signal: AbortSignal.timeout(15_000),
  });
  if (!attRes.ok) {
    throw new Error(`/v1/attestation returned ${attRes.status}`);
  }
  const att = (await attRes.json()) as AttestationResponse;
  console.log(`[verify-deploy] ethAddress:    ${att.ethAddress}`);
  console.log(`[verify-deploy] composeHash:   ${att.composeHash}`);
  console.log(`[verify-deploy] appId:         ${att.appId}`);
  console.log(`[verify-deploy] instanceId:    ${att.instanceId}`);
  console.log(`[verify-deploy] quoteHex:      ${att.quoteHex.slice(0, 16)}...${att.quoteHex.slice(-8)} (${att.quoteHex.length} chars)`);
  console.log(`[verify-deploy] sigChain:      ${att.signatureChainHex.length} entries`);

  if (health.signer !== att.ethAddress) {
    throw new Error(
      `ethAddress mismatch: /health=${health.signer} vs /v1/attestation=${att.ethAddress}`,
    );
  }

  console.log(`[verify-deploy] running verifyReportDataBinding...`);
  verifyReportDataBinding({
    quoteHex: att.quoteHex,
    expectedEthAddress: att.ethAddress,
    expectedComposeHash: att.composeHash,
  });
  console.log(`[verify-deploy] OK — quote binds to (ethAddress, composeHash)`);

  const note = `# Phala Cloud Deployment Evidence

> Auto-generated by \`enclave/phala/scripts/verify-deploy.ts\` at ${new Date().toISOString()}.
> Re-run anytime: \`npx ts-node enclave/phala/scripts/verify-deploy.ts ${baseUrl}\`

## Live deployment

- **Base URL:** ${baseUrl}
- **/health:** \`source: ${health.source}\`, \`signer: ${health.signer}\`
- **Bound at:** ${new Date(att.boundAt * 1000).toISOString()}

## Attestation chain

| Field | Value |
|---|---|
| ethAddress | \`${att.ethAddress}\` |
| composeHash | \`${att.composeHash}\` |
| appId | \`${att.appId}\` |
| instanceId | \`${att.instanceId}\` |
| reportDataHex | \`${att.reportDataHex}\` |
| signatureChain entries | ${att.signatureChainHex.length} |
| quoteHex length | ${att.quoteHex.length} chars |

## Verification

\`verifyReportDataBinding\` against this quote returns OK — the receipt
signing key was provably derived inside the TDX-attested image whose
compose hash matches the value above. Re-run the script any time to
re-verify against the live endpoint.

## Pinned values for the README + verify-receipt CLI

\`\`\`
COMPASS_PHALA_URL=${baseUrl}
COMPASS_TEE_SIGNER_ADDR=${att.ethAddress}
COMPASS_TEE_COMPOSE_HASH=${att.composeHash}
\`\`\`
`;

  const outPath = resolve(__dirname, "../../../docs/notes/phala-deployment.md");
  writeFileSync(outPath, note);
  console.log(`[verify-deploy] evidence written to ${outPath}`);
}

main().catch((e) => {
  console.error(`[verify-deploy] FAIL:`, e);
  process.exit(1);
});
