import type { MetadataRoute } from "next";

// PWA manifest. Renders the install banner on mobile + Add-to-Home-Screen
// affordance on iOS / Android Chrome. Theme color matches the canonical
// black background; icons are generated by app/icon.tsx + app/apple-icon.tsx.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Compass — Prove eligibility, not identity",
    short_name: "Compass",
    description:
      "A private eligibility firewall on 0G. Built for 368,000 HK migrant workers + 27M across APAC. Prove eligibility for services without disclosing identity. Live on Aristotle mainnet.",
    start_url: "/",
    display: "standalone",
    background_color: "#000000",
    theme_color: "#000000",
    icons: [
      { src: "/icon", sizes: "192x192", type: "image/png" },
      { src: "/apple-icon", sizes: "180x180", type: "image/png" },
    ],
    categories: ["productivity", "utilities"],
    lang: "en",
  };
}
